#### T1.Fes un programa amb les següents accions:
#### - Crea 4 variables, a una assigna-li la teva edat, a un altre el teu nom, a un altre el teu cognom i a un altre el valor true si estàs a l'atur o false si no estàs.
#### - Imprimeix aquestes 4 variables anteriors juntament amb la frase "El meu nom és: X, el meu cognom és: Y i tinc Z anys. Estic a l'atur? W"" on X, Y, Z i W són els valors de les variables que has creat abans.
#### - Demana 3 dades més mitjançant 3 promps i printa una frase amb els 3 valors que has demanat (pots inventar la temàtica de les dades que demanis).

In [6]:
edad = 34
nombre = "Iván"
apellido = "Aguilar"
en_paro = True

print(f"El meu nom és: {nombre}, el meu cognom és: {apellido} i tinc {edad}. Estic a l'atur? {en_paro}")

deporte = input("¿Realizas alguna actividad o deporte? ")
comida = input("¿Cuál es la gastronomía que más te gusta? ")
bebida_favorita = input("¿Qué sueles beber cuando comes? ")

print(f"Normalmente, después de trabajo {deporte}. Me encanta la gastronomía {comida} y suelo beber {bebida_favorita} mientras como.")

El meu nom és: Iván, el meu cognom és: Aguilar i tinc 34. Estic a l'atur? True
Normalmente, después de trabajo voy al gimnasio. Me encanta la gastronomía asiática y suelo beber cerveza mientras como.

#### T2.Crea un programa que demani l'edat a l'usuari/ària. Si aquesta és igual o major a 18, el programa ha d'imprimir per pantalla "Ets major d'edat" si no "NO ets major d'edat."

In [ ]:
nombre = input("¿Cómo te llamas?")
edad = int(input("¿Qué edad tinenes?"))

if edad >= 18:
    print("Eres mayor de edad")
else:
    print("No eres mayor de edad")

Eres mayor de edad

##### T3.Modifica el programa anterior i fes que la resposta segons l'edat segueixi aquest algoritme:

##### - Si l'edat és negativa, el programa ha d'imprimir: "una edat negativa no és possible per a una persona."

##### - Si l'edat està entre 0 i 17 (ambdós inclosos), el programa ha d'imprimir: "ets MENOR d'edat."

##### - Si l'edat està entre 18 i 125 (ambdós inclosos), el programa ha d'imprimir: "ets MAJOR d'edat."

##### - Si l'edat és major que 125, el programa ha d'imprimir: "una edat tan alta és difícil de veure en una persona."

In [11]:
nombre = input("¿Cómo te llamas?")
edad = int(input("¿Qué edad tinenes?"))

if edad < 0:
    print("Una edad negativa no es posible para una persona")
elif edad <= 17:
    print("Eres menor de edad")
elif edad <= 125:
    print("Eres mayor de edad")
else:
    print("Una edad tan alta es difícil de ver en una persona")

Eres mayor de edad

#### T4.Crea una funció que demani el nom a l'usuari i mostri un missatge de salutació

In [12]:
def greetings():
    name = input("¿cómo te llamas?")
    print(f"¡Bienvenido al curso, {name}!")

greetings()

¡Bienvenido al curso, Iván!

#### T5.Descripció:
####    1.Crea una funció que rebi un preu i retorni el preu amb IVA (21% per defecte)
####    2.A continuació, demana un preu a l'usuari i mostra el resultat amb l'IVA aplicat

In [ ]:
#primer intento
def precio_final(num):
    resultado = num * 1.21
    return resultado

precio_usuario = float(input("Introduce un precio sin IVA:"))

precio_con_IVA = precio_final(precio_usuario)

print("Precio con IVA:" , precio_con_IVA,"€")

Precio con IVA: 121.0 €

In [ ]:
#otra opción
def precio_final(num):
    resultado = num * 1.21
    return resultado
 
print("Precio con IVA:" , precio_final(float(input("Introduce un precio sin IVA:"))),"€")

Precio con IVA: 121.0 €

In [4]:
#aún más simple
def precio_final(num):
    return num * 1.21
 
print("Precio con IVA:" , precio_final(float(input("Introduce un precio sin IVA:"))),"€")

Precio con IVA: 121.0 €

#### T6. Descripció:
#### 1.Crea una funció que rebi un número enter com a argument i retorni True si el número és parell, o False si és senar.
#### 2.A continuació, demana un número a l'usuari, utilitza la funció i mostra un missatge indicant si el número és parell o senar.

In [6]:
#1
def par_impar(num):
    if num % 2 == 0: #numero par
        return True
    else:            #numero impar
        return False

numero = 100
par_impar(numero)

True

In [7]:
#2
def par_impar(num):
    if int(num) % 2 == 0:
        print("El número",num,"es par")
    else:
        print("El número",num,"es impar")

numero_usuario = input("Introduce un número:")
par_impar(numero_usuario)

El número 50 es par

In [14]:
#versión Lucía
def es_par(numero):
    if numero % 2 == 0:
        return True
    else:
        return False
 
numero = int(input("Introduce un número entero: "))
 
if es_par(numero):
    print("El número es par.")
else:
    print("El número es impar.")

El número es par.

#### T7

#### Exercici 1 
#### Crea una llista amb tres tasques inicials: "netejar la cuina", "treure el gos a passejar" i "portar a la nena al col·legi". Un cop creada, imprimeix-la.
#### Després afegeix al final de la llista, les tasques: "fer esport", "meditar". Torna a imprimir-la per veure que s'han afegit.
#### Elimina la tasca "netejar la cuina" i torna a imprimir la llista.
#### Finalment, afegeix la tasca "cuinar" a la segona posició de la llista.

In [6]:
to_do = ["netejar la cuina","treure el gos a passejar","portar la nena al col·legi"]

print(to_do)

to_do.append("fer esport")
to_do.append("meditar")             

print(to_do)

to_do.remove("netejar la cuina")

print(to_do)

to_do.insert(1,"cuinar")

print(to_do)

['netejar la cuina', 'treure el gos a passejar', 'portar la nena al col·legi']
['netejar la cuina', 'treure el gos a passejar', 'portar la nena al col·legi', 'fer esport', 'meditar']
['treure el gos a passejar', 'portar la nena al col·legi', 'fer esport', 'meditar']
['treure el gos a passejar', 'cuinar', 'portar la nena al col·legi', 'fer esport', 'meditar']

#### Exercici 2
#### Crea un diccionari on puguem determinar quin dia es fa cada tasca. Assigna un dia diferent de la setmana a totes les tasques anteriors.
#### Printa la tasca del dilluns

In [21]:
tareas = {
    "lunes":"sacar el perro a pasear",
    "martes":"cocinar",
    "miercoles":"llevar la niña al colegio",
    "jueves":"hacer deporte",
    "viernes":"meditar",
    "sabado":"ir al supermercado",
    "domingo": "ir a la playa"
    }

print(tareas)

type(tareas)

{'lunes': 'sacar el perro a pasear', 'martes': 'cocinar', 'miercoles': 'llevar la niña al colegio', 'jueves': 'hacer deporte', 'viernes': 'meditar', 'sabado': 'ir al supermercado', 'domingo': 'ir a la playa'}

dict

#### T8
#### Crea una funció que faci el següent:

#### Creï una llista buida.
#### Demani a l’usuari 3 paraules, una per una.
#### Si la paraula comença per 'A' o 'a' i té menys de 7 lletres, afegeix-la a la llista.
#### Si no compleix aquestes condicions, no facis res.
#### Un cop demanades les 3 paraules i avaluades, imprimeix la llista completa.

In [13]:
def contador_palabras():
    lista = []

    palabra1 = input("Introdueix la paraula 1: ")
    if (palabra1.startswith('A') or palabra1.startswith('a')) and len(palabra1) < 7:
        lista.append(palabra1)

    palabra2 = input("Introdueix la paraula 2: ")
    if (palabra2.startswith('A') or palabra2.startswith('a')) and len(palabra2) < 7:
        lista.append(palabra2)

    palabra3 = input("Introdueix la paraula 3: ")
    if (palabra3.startswith('A') or palabra3.startswith('a')) and len(palabra3) < 7:
        lista.append(palabra3)

    print(lista)

contador_palabras()

['amor', 'ave', 'aroma']

#### T9.Crea una funció que rebi com a paràmetre el nombre de paraules que l’usuari/ària vol introduir. A continuació:
#### 1.Demana tantes paraules com hagi indicat l’usuari/ària i desa-les en una llista.
#### 2.Mostra per pantalla totes les paraules introduïdes.
#### Finalment, abans de cridar la funció, demana a l’usuari/ària quantes paraules vol introduir.

In [5]:
def palabras_usuario(numero_palabras):
    lista_palabras = []

    for i in range(numero_palabras):
        palabra = input(f"Introduce la palabra {i+1}: ")
        lista_palabras.append(palabra)

    print("Las palabras son:")
    for palabra in lista_palabras:
        print(palabra)

palabras_usuario(int(input("¿Cuántas palabras quieres introducir? ")))

Las palabras son:
pikachu
squirtle
charmander

In [4]:
#Jordi
def paraules():
    llista_b = []
    nombre = int(input("Quantes paraules vols introduïr?"))
    count = 1
    for i in range(nombre):
        word = input(f"introdueix el mot numero {count}:")
        llista_b.append(word)
        count += 1
    print(llista_b)
 
#nomes cal cridar la funcio i ja demanara el parametre
paraules()

['asdsa', 'asasf', '', '', '']

In [ ]:
#Didac
llista2 = []
 
def num_paraules():
   for x in range (NUM):
      llista2.append(input('Introdueix una paraula'))
   print (llista2)
 
NUM=int(input('Quantes paraules vols introduïr?'))
num_paraules()

#### T10.Defineix una funció que rebi una llista de números i retorni el sumatori de tots els elements (sense utilitzar sum(), fes el càlcul manualment amb un bucle).
#### 1.Crea una llista amb 10 números.
#### 2.Calcula la mitjana fent servir la funció del sumatori.
#### 3.Mostra per pantalla el sumatori i la mitjana.

In [2]:
def sumatorio_numeros(lista_numeros):
    sumatorio = 0

    for i in lista_numeros:
        sumatorio += i
    
    return sumatorio

# 1
numeros = [5,10,15,20,25,30,35,40,45,50]

#2
total = sumatorio_numeros(numeros)
media = total / len(numeros)

#3
print(f"El sumatorio es: {sumatorio_numeros(numeros)} y la media es:{total/len(numeros):.2f}")

El sumatorio es: 275 y la media es:27.50

#### T11.Crea una funció que faci el següent:
#### 1.Demani a l’usuari/ària 5 articles i el seu preu corresponent.
#### 2.Desi aquests articles i preus en un diccionari, on la clau sigui el nom de l’article i el valor, el seu preu.
#### 3.Retorni el diccionari amb les dades introduïdes.
#### Un cop creat el diccionari, imprimeix només els articles que costin menys de 10 euros.

In [4]:
def funcion_articulos():
    articulos = {}

    for i in range(5):
        nombre = input(f"Introduce el nombre del artículo {i+1}: ")
        precio = float(input(f"Introduce el precio de {nombre}"))

        articulos[nombre] = precio

    return articulos

catalogo_articulos = funcion_articulos()

print(catalogo_articulos)

{'nintendo': 350.0, 'muñeco spider-man': 39.0, 'taza': 12.5, 'bolígrafo': 3.89, 'agenda': 16.45}

In [ ]:
def funcion_articulos():
    articulos = {}

    for i in range(5):
        nombre = input(f"Introduce el nombre del artículo {i+1}: ")
        precio = float(input(f"Introduce el precio de {nombre}"))

        articulos[nombre] = precio

    return articulos

catalogo_articulos = funcion_articulos()

print("Artículos que menos de 10 euros:")
for articulo, precio in catalogo_articulos.items():
    if precio < 10:
        print(f"{articulo}: {precio} €")

Artículos que menos de 10 euros:
Taza: 8.99 €
Agenda: 9.8 €
Bolígrafo Pilot: 5.45 €
Libro: 9.68 €
Chocolate M&M's: 4.86 €

### T12
#### 1.Exploració de dades 
Carrega el dataset Salut_i_son.csv i respon les següents preguntes:

- Quantes columnes i quants registres té el dataset?
- Quantes columnes són de tipus enter? I quantes de tipus decimal?
- Quina és l’edat màxima registrada?
- Quina és la duració mínima de la son?
- Quina és la mitjana de la qualitat de la son?
Explica com has trobat cadascuna de les respostes

In [10]:
import pandas as pd

In [11]:
# Cargar el archivo CSV

df = pd.read_csv("Salut_i_son.csv")
df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [10]:
# Revisar si se cargó correctamente

df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [11]:
# Otra forma de revisar si se cargó correctamente

df.head()

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea

In [12]:
# Quantes columnes i quants registres té el dataset?

df.shape

(374, 13)

In [9]:
# Quantes columnes són de tipus enter? I quantes de tipus decimal?

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Person ID                374 non-null    int64
 1   Gender                   374 non-null    object
 2   Age                      374 non-null    int64
 3   Occupation               374 non-null    object
 4   Sleep Duration           374 non-null    float64
 5   Quality of Sleep         374 non-null    int64
 6   Physical Activity Level  374 non-null    int64
 7   Stress Level             374 non-null    int64
 8   BMI Category             374 non-null    object
 9   Blood Pressure           374 non-null    object
 10  Heart Rate               374 non-null    int64
 11  Daily Steps              374 non-null    int64
 12  Sleep Disorder           155 non-null    object
dtypes: float64(1), int64(7), object(5)
memory usage: 38.1+ KB

In [13]:
df.dtypes

Person ID                    int64
Gender                      object
Age                          int64
Occupation                  object
Sleep Duration             float64
Quality of Sleep             int64
Physical Activity Level      int64
Stress Level                 int64
BMI Category                object
Blood Pressure              object
Heart Rate                   int64
Daily Steps                  int64
Sleep Disorder              object
dtype: object

In [15]:
# Otra forma de resolverlo

tipos_datos = df.dtypes
enteros = tipos_datos[tipos_datos == "int64"].count()
decimales = tipos_datos[tipos_datos == "float64"].count()

In [16]:
# Ver cantidad de valores enteros

enteros

np.int64(7)

In [17]:
# Ver cantidad de valores decimales

decimales

np.int64(1)

In [18]:
# Quina és l’edat màxima registrada?

df["Age"].max()

np.int64(59)

In [19]:
# Quina és la duració mínima de la son?

df["Sleep Duration"].min()

np.float64(5.8)

In [20]:
# Quina és la mitjana de la qualitat de la son?

df["Quality of Sleep"].mean()

np.float64(7.31283422459893)

#### 2. Filtres
Classifica les dades en dos grups de persones segons els criteris següents:
- Grup 1: Persones de més de 40 anys, amb una qualitat de la son superior a 8 i que fan més de 5000 passes al dia.
- Grup 2: Persones que treballen com a enginyers/eres o enginyers/eres de software i tenen una heart rate superior a 60.

In [5]:
# Grupo 1: Edad > 40, Calidad del sueño > 8, Pases diarios > 5000
grupo1 = df[
    (df['Age'] > 40) #más de 40 
    & 
    (df['Quality of Sleep'] > 8) #con una calidad de sueño superior a 8
    & 
    (df['Daily Steps'] > 5000) #trecer condición
    ]

grupo1

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
341,342,Female,56,Doctor,8.2,9,90,3,Normal Weight,118/75,65,10000,NaN
342,343,Female,56,Doctor,8.2,9,90,3,Normal Weight,118/75,65,10000,NaN
343,344,Female,57,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,NaN
344,345,Female,57,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
345,346,Female,57,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
346,347,Female,57,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
347,348,Female,57,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
348,349,Female,57,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
349,350,Female,57,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
350,351,Female,57,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
351,352,Female,57,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
352,353,Female,58,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
353,354,Female,58,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
354,355,Female,58,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
355,356,Female,58,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
356,357,Female,58,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
357,358,Female,58,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
358,359,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,NaN
359,360,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,NaN
360,361,Female,59,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
361,362,Female,59,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
362,363,Female,59,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
363,364,Female,59,Nurse,8.2,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
364,365,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
365,366,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
366,367,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
367,368,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
368,369,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea

In [6]:
print("Cantidad en Grupo 1:", len(grupo1))

Cantidad en Grupo 1: 33

In [7]:
# Grupo 2: Ocupación relacionada con ingeniería y heart rate > 60
grupo2 = df[
    (df['Occupation'].str.contains('Engineer', case=False))
    & 
    (df['Heart Rate'] > 60)
    ]

print("Cantidad en Grupo 2: ", len(grupo2))

Cantidad en Grupo 2:  67

In [8]:
# Otra forma de resolver el grupo 2:

print(df['Occupation'].unique())
 
G2_df = df[
    ((df['Occupation'] == 'Softwere Engineer') | (df['Occupation'] == 'Engineer'))
            & (df['Heart Rate'] > 60)]
G2_df

['Software Engineer' 'Doctor' 'Sales Representative' 'Teacher' 'Nurse'
 'Engineer' 'Accountant' 'Scientist' 'Lawyer' 'Salesperson' 'Manager']

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder
50,51,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000,NaN
51,52,Male,32,Engineer,7.5,8,45,3,Normal,120/80,70,8000,NaN
86,87,Male,35,Engineer,7.2,8,60,4,Normal,125/80,65,5000,NaN
87,88,Male,35,Engineer,7.2,8,60,4,Normal,125/80,65,5000,NaN
88,89,Male,35,Engineer,7.3,8,60,4,Normal,125/80,65,5000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,335,Female,54,Engineer,8.4,9,30,3,Normal,125/80,65,5000,NaN
335,336,Female,54,Engineer,8.4,9,30,3,Normal,125/80,65,5000,NaN
336,337,Female,54,Engineer,8.4,9,30,3,Normal,125/80,65,5000,NaN
337,338,Female,54,Engineer,8.4,9,30,3,Normal,125/80,65,5000,NaN
338,339,Female,54,Engineer,8.5,9,30,3,Normal,125/80,65,5000,NaN

#### 3.Agrupacions
Agrupa les dades del dataset original per calcular valors mitjans:
- Calcula la mitjana de la duració de la son agrupada per gènere.
- Calcula la mitjana de la duració de la son agrupada per gènere i ocupació.

In [10]:
# Media de la duración del sueño agrupada por género
df.groupby('Gender')['Sleep Duration'].mean()

Gender
Female    7.229730
Male      7.036508
Name: Sleep Duration, dtype: float64

In [7]:
# Media de la duración del sueño agrupada por género y ocupación
df.groupby(['Gender', 'Occupation'])['Sleep Duration'].mean()

Gender  Occupation
Female  Accountant              7.111111
        Doctor                  8.200000
        Engineer                8.425000
        Lawyer                  7.150000
        Manager                 6.900000
        Nurse                   7.063014
        Scientist               6.000000
        Teacher                 6.705714
Male    Accountant              7.200000
        Doctor                  6.934783
        Engineer                7.535484
        Lawyer                  7.422222
        Sales Representative    5.900000
        Salesperson             6.403125
        Software Engineer       6.750000
        Teacher                 6.580000
Name: Sleep Duration, dtype: float64

#### 4.Modificació de columnes
- Afegeix una nova columna al DataFrame, anomenada "Poca Son", amb el valor True
- Elimina les últimes 4 columnes del DataFrame original i desa el nou DataFrame en una variable anomenada sleep_info.

In [12]:
# Añade una nueva columna al DataFrame, llamada "Poca Son"
# con el valor True si la persona duerme menos de 7 horas y False en caso contrario

df["Poca Son"] = df["Sleep Duration"] < 7

df

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure,Heart Rate,Daily Steps,Sleep Disorder,Poca Son
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83,77,4200,NaN,True
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN,True
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80,75,10000,NaN,True
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,True
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90,85,3000,Sleep Apnea,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,False
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,False
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,False
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,False
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95,68,7000,Sleep Apnea,False

In [13]:
# Elimina las últimas 4 columnas del DataFrame original y guarda el nuevo DataFrame en una variable llamada sleep_info

df.drop(df.columns[-4:], axis=1, inplace=True)

sleep_info = df

sleep_info

,Person ID,Gender,Age,Occupation,Sleep Duration,Quality of Sleep,Physical Activity Level,Stress Level,BMI Category,Blood Pressure
0,1,Male,27,Software Engineer,6.1,6,42,6,Overweight,126/83
1,2,Male,28,Doctor,6.2,6,60,8,Normal,125/80
2,3,Male,28,Doctor,6.2,6,60,8,Normal,125/80
3,4,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90
4,5,Male,28,Sales Representative,5.9,4,30,8,Obese,140/90
...,...,...,...,...,...,...,...,...,...,...
369,370,Female,59,Nurse,8.1,9,75,3,Overweight,140/95
370,371,Female,59,Nurse,8.0,9,75,3,Overweight,140/95
371,372,Female,59,Nurse,8.1,9,75,3,Overweight,140/95
372,373,Female,59,Nurse,8.1,9,75,3,Overweight,140/95
373,374,Female,59,Nurse,8.1,9,75,3,Overweight,140/95

### T13
#### Descripció
La nostra empresa es dedica a realitzar anàlisis de dades geogràfiques i socials, i un client ens ha sol·licitat una eina per identificar dades bàsiques de cada continent de manera automàtica.

1.Per això, cal crear una funció que rebi dos paràmetres:
- Un DataFrame amb informació de països (com el del fitxer Country.xlsx)
- El nom d’un continent (com a cadena de text)

In [14]:
import pandas as pd

In [15]:
# Cargar DataFrame 

df_country = pd.read_csv("Country(in).csv", sep=";", encoding="latin-1")

df_country

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,"Code2,"
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,"AW,"
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,"AF,"
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,"AO,"
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,"AI,"
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,"AL,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,"YE,"
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Kotunica,1792.0,"YU,"
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,"ZA,"
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,"ZM,"
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,"ZW,"

#### 1.Per això, cal crear una funció que rebi dos paràmetres:
- Un DataFrame amb informació de països (com el del fitxer Country.xlsx)
- El nom d’un continent (com a cadena de text)
#### 2.La funció ha de retornar un diccionari amb les següents dades relacionades amb el continent indicat:
- Nombre de regions diferents que hi ha dins del continent.
- Nombre de països dins del continent.
- Superfície màxima (SurfaceArea) registrada al continent.
- Superfície mínima registrada.
- Població mitjana (Population) dels països del continent.
- Mitjana de l’esperança de vida (LifeExpectancy) dels països del continent.
#### 3.Finalment, carrega el fitxer adjunt amb la següent instrucció:
- data = pd.read_csv("arxiu csv", sep=";", encoding="latin-1") Ejecutar antes #Cargar DataFrame

Executa la funció per a diversos continents i mostra els resultats obtinguts.

In [16]:
def resumen_continente(df, continente):
    df_filtrado = df[df["Continent"] == continente] # filtrado por "continente"
    resumen = {
        "Regiones distintas": df_filtrado["Region"].nunique(), # número de regiones diferentes que hay dentro del continente
        "Número de países": df_filtrado["Name"].count(), # número de países dentro del continente
        "Superficie máxima": df_filtrado["SurfaceArea"].max(), # superficie máxima registrada en el continente
        "Superficie mínima": df_filtrado["SurfaceArea"].min(), # superficie mínima registrada
        "Población media": df_filtrado["Population"].mean(), # población media de los países del continente
        "Esperanza de vida promedio": df_filtrado["LifeExpectancy"].mean() # promedio de la esperanza de vida de los países del contiente
    }
    
    return resumen

In [17]:
df_country["Continent"].unique()

array(['North America', 'Asia', 'Africa', 'Europe', 'South America',
       'Oceania', 'Antarctica'], dtype=object)

In [18]:
resumen_continente(df_country, "Oceania")

{'Regiones distintas': 5,
 'Número de países': np.int64(28),
 'Superficie máxima': np.float64(7741220.0),
 'Superficie mínima': np.float64(12.0),
 'Población media': np.float64(1085755.357142857),
 'Esperanza de vida promedio': np.float64(69.71499999999999)}

### T14
#### Descripció
La nostra empresa està col·laborant amb una ONG que estudia la distribució de l'espai i dels recursos geogràfics en relació amb la població mundial. L’objectiu és identificar quins països tenen menys espai disponible per habitant, fet que pot estar relacionat amb situacions de sobrepoblació, pressió urbana o desigualtat en l’ús del territori.

Per dur a terme aquest estudi, ens han proporcionat un conjunt de dades (Country(in).csv) que conté informació detallada sobre la població, la superfície i altres atributs de cada país.

Crea una funció en Python que rebi com a paràmetres:
1. Un DataFrame amb dades de països.
2. El nombre n de països que es volen obtenir com a resultat.

La funció ha de calcular, per a cada país, la quantitat de metres quadrats disponibles per persona, utilitzant la següent fórmula:

Metres per persona = SurfaceArea × 1.000.000 / Population

La funció ha de retornar els n països amb menys espai disponible per habitant.

Executa la funció per obtenir els 10 països amb menys espai per persona i després per obtenir-ne 20.

In [1]:
import pandas as pd

df_country = pd.read_csv("Country(in).csv", sep=";", encoding="latin-1")
df_country

,Code,Name,Continent,Region,SurfaceArea,IndepYear,Population,LifeExpectancy,GNP,GNPOld,LocalName,GovernmentForm,HeadOfState,Capital,"Code2,"
0,ABW,Aruba,North America,Caribbean,193.0,NaN,103000,78.4,828.0,793.0,Aruba,Nonmetropolitan Territory of The Netherlands,Beatrix,129.0,"AW,"
1,AFG,Afghanistan,Asia,Southern and Central Asia,652090.0,1919.0,22720000,45.9,5976.0,NaN,Afganistan/Afqanestan,Islamic Emirate,Mohammad Omar,1.0,"AF,"
2,AGO,Angola,Africa,Central Africa,1246700.0,1975.0,12878000,38.3,6648.0,7984.0,Angola,Republic,José Eduardo dos Santos,56.0,"AO,"
3,AIA,Anguilla,North America,Caribbean,96.0,NaN,8000,76.1,63.2,NaN,Anguilla,Dependent Territory of the UK,Elisabeth II,62.0,"AI,"
4,ALB,Albania,Europe,Southern Europe,28748.0,1912.0,3401200,71.6,3205.0,2500.0,Shqipëria,Republic,Rexhep Mejdani,34.0,"AL,"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
234,YEM,Yemen,Asia,Middle East,527968.0,1918.0,18112000,59.8,6041.0,5729.0,Al-Yaman,Republic,Ali Abdallah Salih,1780.0,"YE,"
235,YUG,Yugoslavia,Europe,Southern Europe,102173.0,1918.0,10640000,72.4,17000.0,NaN,Jugoslavija,Federal Republic,Vojislav Kotunica,1792.0,"YU,"
236,ZAF,South Africa,Africa,Southern Africa,1221037.0,1910.0,40377000,51.1,116729.0,129092.0,South Africa,Republic,Thabo Mbeki,716.0,"ZA,"
237,ZMB,Zambia,Africa,Eastern Africa,752618.0,1964.0,9169000,37.2,3377.0,3922.0,Zambia,Republic,Frederick Chiluba,3162.0,"ZM,"
238,ZWE,Zimbabwe,Africa,Eastern Africa,390757.0,1980.0,11669000,37.8,5951.0,8670.0,Zimbabwe,Republic,Robert G. Mugabe,4068.0,"ZW,"

Crea una funció en Python que rebi com a paràmetres:
1. Un DataFrame amb dades de països.
2. El nombre n de països que es volen obtenir com a resultat.

La funció ha de calcular, per a cada país, la quantitat de metres quadrats disponibles per persona, utilitzant la següent fórmula:

Metres per persona = SurfaceArea × 1.000.000 / Population

La funció ha de retornar els n països amb menys espai disponible per habitant.

In [9]:
def menos_espacio(df, n):
    df["Metros_por_persona"] = (df["SurfaceArea"] * 1_000_000) /df["Population"]
    return df.sort_values(by="Metros_por_persona").head(n)[["Name", "Metros_por_persona"]]

In [3]:
menos_espacio(df_country, 10)

                              Name  Metros_por_persona
129                          Macao           38.054968
131                         Monaco           44.117647
92                       Hong Kong          158.507815
186                      Singapore          173.254836
79                       Gibraltar          240.000000
225  Holy See (Vatican City State)          400.000000
28                         Bermuda          815.384615
139                          Malta          831.141504
134                       Maldives         1041.958042
21                      Bangladesh         1114.923929

In [4]:
menos_espacio(df_country, 20)

                              Name  Metros_por_persona
129                          Macao           38.054968
131                         Monaco           44.117647
92                       Hong Kong          158.507815
186                      Singapore          173.254836
79                       Gibraltar          240.000000
225  Holy See (Vatican City State)          400.000000
28                         Bermuda          815.384615
139                          Malta          831.141504
134                       Maldives         1041.958042
21                      Bangladesh         1114.923929
23                         Bahrain         1124.797407
31                        Barbados         1592.592593
217                         Taiwan         1625.988497
161                          Nauru         1750.000000
147                      Mauritius         1761.658031
0                            Aruba         1873.786408
176                      Palestine         2017.736214
116                    South Korea         2122.662454
216                         Tuvalu         2166.666667
193                     San Marino         2259.259259

In [ ]:
def menos_espacio(df, n):
    df["Metros_por_persona"] = (df["SurfaceArea"] * 1_000_000) /df["Population"]
    return df.sort_values(["Metros_por_persona"], ascending=True).head(n)[["Name", "Metros_por_persona"]]

# aquí se usar sort_values sin el "by" y con ascending=True

In [8]:
menos_espacio(df_country, 10)

                              Name  Metros_por_persona
129                          Macao           38.054968
131                         Monaco           44.117647
92                       Hong Kong          158.507815
186                      Singapore          173.254836
79                       Gibraltar          240.000000
225  Holy See (Vatican City State)          400.000000
28                         Bermuda          815.384615
139                          Malta          831.141504
134                       Maldives         1041.958042
21                      Bangladesh         1114.923929